### PR TITLE
fix index out of bound bug when comparing ZLabelSets

### LINKED ISSUE #3515: query-frontend 0.17.1: runtime error: index out of range
I faced runtime error: `index out of range [7] with length 7` in query-frontend 0.17.1. There were huge amount of such errors (I suppose on each request), attached full log for one such error.
Unfortunately I do not know how to reproduce it, so far it happened only once.
[query-frontend-0.17.1.err.log](https://github.com/thanos-io/thanos/files/5614135/query-frontend-0.17.1.err.log)

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <yb532204897@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Fixes #3515 

The bug is originated from that I got the label pair length using `Size()` method, it is a stupid mistake :-1:  because it doesn't return the number of label pairs.
Added one test case to ensure no panic for comparing the same label sets.
However, we deduplicate the series before sorting them so the case shouldn't happen. Still investigating the root cause and trying to reproduce this from the query frontend side.

### CODE REVIEW

**Comment by metalmatze** [comment]
Generally looking good. Some other pair of eyes would be good, as I'm not too familiar with this part.

File: pkg/queryfrontend/labels_codec.go [hunk 1]
```diff
@@ -87,8 +87,25 @@ func (c labelsCodec) MergeResponse(responses ...queryrange.Response) (queryrange
 		if len(responses) == 1 {
 			return responses[0], nil
 		}
-		seriesData := make(labelpb.ZLabelSets, 0)
 
+		i := 0
+		var resp queryrange.Response
+		for _, response := range responses {
+			if len(response.(*ThanosSeriesResponse).Data) > 0 {
```
Comment (bwplotka) [inline pkg/queryfrontend/labels_codec.go:94]: I don't get this, why we cannot check this in loop below?

File: pkg/queryfrontend/queryrange_codec.go [hunk 2]
```diff
@@ -111,7 +111,7 @@ func (c queryRangeCodec) DecodeRequest(_ context.Context, r *http.Request) (quer
 		result.ReplicaLabels = r.Form[queryv1.ReplicaLabelsParam]
 	}
 
-	result.StoreMatchers, err = parseMatchersParam(r.Form[queryv1.StoreMatcherParam])
+	result.StoreMatchers, err = parseMatchersParam(r.Form[queryv1.StoreMatcherParam], queryv1.StoreMatcherParam)
```
Comment (bwplotka) [inline pkg/queryfrontend/queryrange_codec.go:114]: This is bad code smell - passing same information twice. Maybe we should pass just `Form` and `matcherKey` to param function?

File: pkg/store/labelpb/label.go [hunk 3]
```diff
@@ -307,7 +307,8 @@ func (z ZLabelSets) Less(i, j int) bool {
 	l := 0
 	r := 0
 	var result int
-	for l < z[i].Size() && r < z[j].Size() {
+	lenI, lenJ := len(z[i].Labels), len(z[j].Labels)
```
Comment (bwplotka) [inline pkg/store/labelpb/label.go:310]: :+1:  (:

**Review by bwplotka — APPROVED** [review]
Thanks, but would be amazing to not have unrelated to fix changes in quick bug fix PR. 

Since you have those, there are minor issues/suggestions for unrelated changes, otherwise LGTM

File: pkg/queryfrontend/queryrange_codec.go (hunk 2 above)
Comment (yeya24) [reply pkg/queryfrontend/queryrange_codec.go:114]: Good point.

File: pkg/queryfrontend/labels_codec.go (hunk 1 above)
Comment (yeya24) [reply pkg/queryfrontend/labels_codec.go:94]: Makes sense. As you mentioned I ll remove this change since it is unrelated and fix them in next master

File: pkg/store/labelpb/label.go (hunk 3 above)
Comment (yeya24) [reply pkg/store/labelpb/label.go:310]: :(

**Comment by yeya24** [comment]
Hi, please take a look again. @bwplotka  @metalmatze

**Review by bwplotka — APPROVED** [review]
Awesome! Thanks :muscle:

**Comment by bwplotka** [comment]
We need changelog but we can add on release PR

**Comment by iyacontrol** [comment]
when release v0.17.2 ? i meet this bug, so had to go back v0.16.0.
