### PR TITLE
Handling of bare path prefix in Querier

### LINKED ISSUE #3180: query-frontend: redirect loop when visiting bare path prefix like `/thanos`
**Thanos, Prometheus and Golang version used**:

```
$ thanos --version
thanos, version 0.15.0 (branch: HEAD, revision: fbd14b49f95e7543883fedf9381a21127d4dda2b)
  build user:       root@d35b081d3e19
  build date:       20200907-09:29:21
  go version:       go1.14.2
```

**What happened**:

When using query-frontend with query that uses a path prefix, we encounter a 301 loop and `ERR_TOO_MANY_REDIRECTS` error when visiting the path prefix, such as `http://localhost/thanos/` but a successful page load on `http://localhost/thanos/graph`. Visiting `http://localhost/thanos/` on *query* correctly redirects to `/thanos/graph`

With curl:

```
$ curl "localhost:9093/thanos/"
<a href="/thanos/">Moved Permanently</a>.

$ curl "localhost:9092/thanos/"
<a href="/thanos/graph">Found</a>.

```

**What you expected to happen**: visiting bare path on query-frontend to 302 to path prefix + `/graph`

**How to reproduce it (as minimally and precisely as possible)**:

1. Run thanos query (port 9092) and query-frontend (port 9093) together with cli args:

```
thanos query --http-address=127.0.0.1:9092 --web.route-prefix=thanos --web.external-prefix=thanos ...

thanos query-frontend --http-address=127.0.0.1:9093 --query-frontend.compress-responses --query-frontend.downstream-url=http://127.0.0.1:9092 --query-range.split-interval=24h --query-range.max-retries-per-request=5 --query-frontend.log_queries_longer_than=5s --query-range.response-cache-config-file=/etc/thanos/range_cache.yml
```

2. Compare request to query with path prefix:

```
$ curl -vsL http://localhost:9092/thanos | head
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9092 (#0)
> GET /thanos HTTP/1.1
> Host: localhost:9092
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: /thanos/
< Date: Wed, 16 Sep 2020 16:39:14 GMT
< Content-Length: 43
<
* Ignoring the response-body
{ [43 bytes data]
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9092/thanos/'
* Found bundle for host localhost: 0x7f989e41c960 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (::1) port 9092 (#0)
> GET /thanos/ HTTP/1.1
> Host: localhost:9092
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Content-Type: text/html; charset=utf-8
< Location: /thanos/graph
< Date: Wed, 16 Sep 2020 16:39:14 GMT
< Content-Length: 36
<
* Ignoring the response-body
{ [36 bytes data]
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9092/thanos/graph'
* Found bundle for host localhost: 0x7f989e41c960 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (::1) port 9092 (#0)
> GET /thanos/graph HTTP/1.1
> Host: localhost:9092
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Wed, 16 Sep 2020 16:39:14 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
<
{ [5494 bytes data]
* Connection #0 to host localhost left intact
* Closing connection 0
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="robots" content="noindex,nofollow">
        <title>Thanos long term storage Prometheus solution</title>
        <link rel="shortcut icon" href="/thanos/static/img/favicon.ico?v=fbd14b49f95e7543883fedf9381a21127d4dda2b">
        <script src="/thanos/static/vendor/js/jquery-3.5.0.min.js?v=fbd14b49f95e7543883fedf9381a21127d4dda2b"></script>
        <script src="/thanos/static/vendor/js/popper.min.js?v=fbd14b49f95e7543883fedf9381a21127d4dda2b"></script>
        <script src="/thanos/static/vendor/bootstrap-4.1.3/js/bootstrap.min.js?v=fbd14b49f95e7543883fedf9381a21127d4dda2b"></script>
```

3. Compare query above with query-frontend request with path prefix:

```
» curl -vsL http://localhost:9093/thanos | head
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9093 (#0)
> GET /thanos HTTP/1.1
> Host: localhost:9093
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Length: 43
< Content-Type: text/html; charset=utf-8
< Date: Wed, 16 Sep 2020 16:40:49 GMT
< Location: /thanos/
< Vary: Accept-Encoding
< Vary: Accept-Encoding
<
* Ignoring the response-body
{ [43 bytes data]
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9093/thanos/'
* Found bundle for host localhost: 0x7f97f0c0d420 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (::1) port 9093 (#0)
> GET /thanos/ HTTP/1.1
> Host: localhost:9093
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Length: 43
< Content-Type: text/html; charset=utf-8
< Date: Wed, 16 Sep 2020 16:40:49 GMT
< Location: /thanos/
< Vary: Accept-Encoding
< Vary: Accept-Encoding
<
* Ignoring the response-body
{ [43 bytes data]
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost:9093/thanos/'
* Found bundle for host localhost: 0x7f97f0c0d420 [can pipeline]
* Could pipeline, but not asked to!
* Re-using existing connection! (#0) with host localhost
* Connected to localhost (::1) port 9093 (#0)
> GET /thanos/ HTTP/1.1
> Host: localhost:9093
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Length: 43
< Content-Type: text/html; charset=utf-8
< Date: Wed, 16 Sep 2020 16:40:49 GMT
< Location: /thanos/
< Vary: Accept-Encoding
< Vary: Accept-Encoding
<
...
* Ignoring the response-body
{ [43 bytes data]
* Connection #0 to host localhost left intact
* Maximum (50) redirects followed
* Closing connection 0
```

### PR DESCRIPTION
**Pull request by aribalam**
Signed-off-by: aribalam <arib.alam.iitkgp@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Fixes #3180 

The details of the approach are given in [this comment](https://github.com/thanos-io/thanos/issues/3180#issuecomment-696401479).

## Verification

Setup: 

```
$ thanos query --http-address=127.0.0.1:9092 --web.route-prefix=thanos --web.external-prefix=thanos
$ thanos query-frontend --http-address=127.0.0.1:9093 --query-frontend.compress-responses --query-frontend.downstream-url=http://127.0.0.1:9092 --query-range.split-interval=24h --query-range.max-retries-per-request=5
```

The following request was made -

```
$ curl -iL --max-redirs 3 http://localhost:9093/thanos
TTP/1.1 302 Found
Content-Length: 36
Content-Type: text/html; charset=utf-8
Date: Mon, 21 Sep 2020 22:04:28 GMT
Location: /thanos/graph
Vary: Accept-Encoding
Vary: Accept-Encoding

HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Mon, 21 Sep 2020 22:04:28 GMT
Vary: Accept-Encoding
Vary: Accept-Encoding
Transfer-Encoding: chunked

<!DOCTYPE html>
<html lang="en">
<-- truncated -->
</html>
```

### CODE REVIEW

File: cmd/thanos/query.go [hunk 1]
```diff
@@ -421,6 +421,9 @@ func runQuery(
 			router.Get("/", func(w http.ResponseWriter, r *http.Request) {
 				http.Redirect(w, r, webRoutePrefix, http.StatusFound)
```
Comment (prmsrswt) [inline cmd/thanos/query.go:422]: We can directly add the redirect to `webRoutePrefix+"/graph"` here so that we don't need to follow two redirects to get at the same place. Instead of `/` -> `/prefix` -> `/prefix/graph` directly redirecting `/` -> `/prefix/graph` would be better.

Comment (bwplotka) [reply cmd/thanos/query.go:422]: :+1:

**Review by prmsrswt — APPROVED** [review]
LGTM!
