### PR TITLE
Fix downsampling option in querier URL

### LINKED ISSUE #1463: Downsampling option not contained in Thanos URL
**Thanos, Prometheus and Golang version used**

<table class="table table-sm table-bordered table-striped table-hover">
      <tbody>
        <tr>
          <th scope="row">Version</th>
          <td>0.6.0</td>
        </tr>
        <tr>
          <th scope="row">Revision</th>
          <td>c70b80eb83e52f5013ed5ffab72464989c132883</td>
        </tr>
        <tr>
          <th scope="row">Branch</th>
          <td>HEAD</td>
        </tr>
        <tr>
          <th scope="row">BuildUser</th>
          <td>circleci@090532e54e70</td>
        </tr>
        <tr>
          <th scope="row">BuildDate</th>
          <td>20190718-11:16:14</td>
        </tr>
        <tr>
          <th scope="row">GoVersion</th>
          <td>go1.12.5</td>
        </tr>
      </tbody>
    </table>

**What happened**

When creating ad-hoc queries in Thanos UI, the URI contains all parameters required to reconstruct the queries. This is very helpful to send eg. a link to a co-worker to share an analysis, or to check from one Thanos environment to another by changing the URI.

Example partial URL:

    /graph?g0.range_input=1h&g0.expr=count(kube_pod_info)&g0.tab=0

Screenshot showing scaledown option

The URI misses the the auto scale down option, though, which has to be set up for all queries after opening the URI.

**What you expected to happen**

Downsampling option contained in the URI

**How to reproduce it (as minimally and precisely as possible)**:

Change downsampling option, observe URI

**Full logs to relevant components**

**Anything else we need to know**

### PR DESCRIPTION
**Pull request by obiesmans**
Fixes #1463 

* Downsampling option in Querier UI is now reflected in the URL.

### CODE REVIEW

**Comment by obiesmans** [comment]
Amended the pr to use camelcase and have a max_source_resolution in URL, as in the documentation.

File: pkg/ui/static/js/graph_template.handlebar [hunk 1]
```diff
@@ -115,7 +115,7 @@
                         <div class="prometheus_input_group pull-left">
                            <select name="max_source_resolution_input" title="Downsampling option" id="max_source_resolution_input{{id}}">
                               <option value="">Auto downsampling</option>
-                              <option selected="selected" value="0s">Only raw data</option>
+                              <option value="0s">Only Raw data</option>
```
Comment (GiedriusS) [inline pkg/ui/static/js/graph_template.handlebar]: Why did you take off `selected` here and converted it into `Raw`? It is changing the defaults AFAICT :(

File: pkg/ui/static/js/graph.js [hunk 2]
```diff
@@ -390,6 +393,9 @@ Prometheus.Graph.prototype.getOptions = function() {
       }
     }
   });
+
+  options.max_source_resolution = self.queryForm.find("select[name=max_source_resolution_input]").val();
```
Comment (GiedriusS) [inline pkg/ui/static/js/graph.js]: Maybe `select[name=max_source_resolution_input]` should be moved out somewhere because we are repeating ourselves?

**Comment by GiedriusS** [comment]
Everything works, just those two comments and we should be good to go :smile:

File: pkg/ui/static/js/graph_template.handlebar (hunk 1 above)
Comment (obiesmans) [reply pkg/ui/static/js/graph_template.handlebar]: Converted Raw back, selected is still off, but now the code select "0s" if max_source_resolution is undefined. This keeps the default comportment to "Only raw data".

File: pkg/ui/static/js/graph.js (hunk 2 above)
Comment (obiesmans) [reply pkg/ui/static/js/graph.js]: Refactored the 3 occurrences as `maxSourceResolutionInput`.

**Comment by obiesmans** [comment]
Thanks a lot for the review ! Sorry I didn't reply sooner, was off for a few days.
I pushed an update that addresses @GiedriusS comments.

I also ran into issues where the URL params format didn't allow for empty params. 
I thought that correcting this would make maintaining against the upstream prometheus UI harder, so instead I put "auto" as keyword in the UI and normalized it back to an empty string when submitting the query. Is it OK with you ?

File: pkg/ui/static/js/graph.js [hunk 3]
```diff
@@ -521,7 +530,11 @@ Prometheus.Graph.prototype.submitQuery = function() {
   var startTime = new Date().getTime();
   var rangeSeconds = self.parseDuration(self.rangeInput.val());
   var resolution = parseInt(self.queryForm.find("input[name=step_input]").val()) || Math.max(Math.floor(rangeSeconds / 250), 1);
-  var maxSourceResolution = self.queryForm.find("select[name=max_source_resolution_input]").val();
+  var maxSourceResolution = self.maxSourceResolutionInput.val()
+  // normalize max_source_resolution parameter
+  if ( maxSourceResolution == "auto") {
```
Comment (bwplotka) [inline pkg/ui/static/js/graph.js]: Why not instead supporting `auto` value in Thanos Querier server side? :thinking:

Comment (obiesmans) [reply pkg/ui/static/js/graph.js]: Yes I like the idea.
Should I add this to this PR or open another PR ?

Comment (obiesmans) [reply pkg/ui/static/js/graph.js]: Also remember that grafana users can't set this parameter and probably want the "auto" parameter as default.

File: pkg/ui/static/js/graph_template.handlebar [hunk 4]
```diff
@@ -114,8 +114,8 @@
 
                         <div class="prometheus_input_group pull-left">
                            <select name="max_source_resolution_input" title="Downsampling option" id="max_source_resolution_input{{id}}">
-                              <option value="">Auto downsampling</option>
-                              <option selected="selected" value="0s">Only raw data</option>
+                              <option value="auto">Auto downsampling</option>
+                              <option value="0s">Only raw data</option>
```
Comment (bwplotka) [inline pkg/ui/static/js/graph_template.handlebar]: Quick silly question, why we remove `selected` here again? It changes what is by default set, right?

Comment (GiedriusS) [reply pkg/ui/static/js/graph_template.handlebar]: Makes sense IMHO that we keep all of that logic together in that file instead of the HTML code, thanks for pointing this out!

**Comment by GiedriusS** [comment]
Also, double-checked the "instant query" side of this - everything should work well like before and now actually the user will be able to see that they are able to change this parameter -- it was "invisible" before.

**Comment by obiesmans** [comment]
Thanks a lot for take the time to review this @GiedriusS !
