### PR TITLE
Store: fix returned labels on external label conflict when skipping chunks

### LINKED ISSUE #6844: Descrepancy in labels using api/v1/series and api/v1/query when external label and internal label has the same key
Hello, 

I am using Thanos 0.32.5.

**Issue:**
It was noticed flaky issue, that Thanos always exposing external_label when executing queries. But it randomly giving external_label or internal_label value when labels key is the same when querieng api/v1/series.

Here is prometheus output:
image

And after application external_label, the new label cluster shows in thanos:
image

But when I am querieng api/v1/series endpoint, it randomly gives value of cluster:
`{
  "status": "success",
  "data": [
    {
      "__name__": "collectd_collectd_queue_length",
      "cassandra_datastax_com_cluster": "cassandra",
      "cassandra_datastax_com_datacenter": "dc1",
      "cluster": "cassandra",
      "collectd": "write_queue",
      "container": "cassandra",
      "dc": "dc1",
      "endpoint": "prometheus",
      "exported_instance": "10.2.150.192",
      "instance": "10.2.150.192:9103",
      "job": "cassandra-dc1-all-pods-service",
      "namespace": "cit1-core",
      "pod": "cassandra-dc1-r2-sts-0",
      "prometheus": "monitoring/kube-prometheus-stack-prometheus",
      "prometheus_replica": "prometheus-kube-prometheus-stack-prometheus-0",
      "rack": "r2",
      "service": "cassandra-dc1-all-pods-service"
    },
    {
      "__name__": "collectd_collectd_queue_length",
      "cassandra_datastax_com_cluster": "cassandra",
      "cassandra_datastax_com_datacenter": "dc1",
      "cluster": "cassandra",
      "collectd": "write_queue",
      "container": "cassandra",
      "dc": "dc1",
      "endpoint": "prometheus",
      "exported_instance": "10.2.151.7",
      "instance": "10.2.151.7:9103",
      "job": "cassandra-dc1-all-pods-service",
      "namespace": "cit1-core",
      "pod": "cassandra-dc1-r3-sts-0",
      "prometheus": "monitoring/kube-prometheus-stack-prometheus",
      "prometheus_replica": "prometheus-kube-prometheus-stack-prometheus-0",
      "rack": "r3",
      "service": "cassandra-dc1-all-pods-service"
    }
  ]
}`

**Expected:**
Any api call should prioritise external_label and return it as a result of request.

**Possible solution:**
 The current solution is to rename internal label in scrape config. But mostly we are using configs via helm out of the box. Meaning, we do not set configs. Therefore, there is a chance external label match some random label from some random metric. Since that, this is worth to fix discrepancy.
Series api endpoint is used by Grafana.

### PR DESCRIPTION
**Pull request by MichaHoffmann**
* [x] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

When skipping chunks we would send invalid labelsets in prometheus store if external and inner labels conflicted

## Verification

Added a acceptance testcase

Fixes #6844

### CODE REVIEW

**Review by GiedriusS — APPROVED** [review]

**Review by yeya24 — APPROVED** [review]
Thanks for the buf fix!

File: pkg/store/prometheus.go [hunk 1]
```diff
@@ -189,15 +189,17 @@ func (p *PrometheusStore) Series(r *storepb.SeriesRequest, seriesSrv storepb.Sto
...
-			lset := make([]labelpb.ZLabel, 0, len(lbm)+finalExtLset.Len())
+			b.Reset(labels.EmptyLabels())
 			for k, v := range lbm {
-				lset = append(lset, labelpb.ZLabel{Name: k, Value: v})
+				b.Set(k, v)
 			}
-			lset = append(lset, labelpb.ZLabelsFromPromLabels(finalExtLset)...)
-			sort.Slice(lset, func(i, j int) bool {
-				return lset[i].Name < lset[j].Name
+			// external labels should take precedence
```
Comment (SuperQ) [inline pkg/store/prometheus.go:198]: I think it would be good to include the fixed behavior in the changelog. Otherwise it's unclear what the "fix" does in the case of conflicts.

Comment (MichaHoffmann) [reply pkg/store/prometheus.go:198]: On conflict external labes take precedence over internal ones ( in thanos )
