### PR TITLE
pkg/rules: consider group name and file for deduplication

### LINKED ISSUE #3017: Thanos Querier Rules API merges rules with the same name but different fields
**Thanos, Prometheus and Golang version used**:

Thanos: 0.14.0
Prometheus: 2.20.0
Golang: golang-1.14

**Object Storage Provider**:

N/A

**What happened**:

Given the following rules file structure in Prometheus:

```
$ jq '.data.groups[] | { name: .name, file: .file} | select(.name == "general.rules")' rules.json
{
  "name": "general.rules",
  "file": "/etc/prometheus/rules/prometheus-k8s-rulefiles-0/openshift-cluster-machine-approver-machineapprover-rules.yaml"
}
{
  "name": "general.rules",
  "file": "/etc/prometheus/rules/prometheus-k8s-rulefiles-0/openshift-monitoring-prometheus-k8s-rules.yaml"
}
{
  "name": "general.rules",
  "file": "/etc/prometheus/rules/prometheus-k8s-rulefiles-0/openshift-sdn-networking-rules.yaml"
}
```

Thanos querier rules `/api/v1/rules`  deduplicates by `name` field only, yielding either:

```
$ jq '.data.groups[] | { name: .name, file: .file} | select(.name == "general.rules")' rules-thanos.json
{
  "name": "general.rules",
  "file": "/etc/prometheus/rules/prometheus-k8s-rulefiles-0/openshift-monitoring-prometheus-k8s-rules.yaml"
} 
```

or, non-deterministically, any other file name from the above Prometheus examples.

This is according to the specification https://github.com/thanos-io/thanos/blob/master/docs/proposals/202003_thanos_rules_federation.md#rules-api:

"Deduplication happens first at the rule group level. **The identifier is the group name**."

**What you expected to happen**:

That is about to be discussed. Either:

1. we add the `file` field as part of the deduplication logic.
2. we sort and explicitly add all `file` names, i.e. comma-separated in the resulting group.
3. additional ideas?

**How to reproduce it (as minimally and precisely as possible)**:

Deploy the examples above with the same group names but different file fields.

**Full logs to relevant components**:

not relevant

**Anything else we need to know**:

once we reach consensus I am happy to augment

### PR DESCRIPTION
**Pull request by s-urbaniak**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

Fixes #3017

## Changes

Currently only the group name is considered for group deduplication.
However prometheus uses also the group file according to [1].

This fixes it.

[1] https://github.com/prometheus/prometheus/blob/ce838ad6fcbd14b0cf9971a4d093ad672e1469fe/rules/manager.go#L1047-L1055

## Verification

Tests have been modified

### CODE REVIEW

**Comment by s-urbaniak** [comment]
cc @simonpasquier @bwplotka @GiedriusS @lilic @yeya24 :)

File: pkg/rules/rulespb/custom.go [hunk 1]
```diff
@@ -186,6 +186,27 @@ func (r *RuleGroups) MarshalJSON() ([]byte, error) {
 	return json.Marshal((*plain)(r))
 }
 
+// Compare compares rule group x and y and returns:
+//
+//   < 0 if x < y   if rule group r1 is not equal and lexically before rule group r2
+//     0 if x == y  if rule group r1 is logically equal to r2 (r1 and r2 are the "same" rule groups)
+//   > 0 if x > y   if rule group r1 is not equal and lexically after rule group r2
+//
+// For sorting this makes sure that more "critical" alert states come first.
```
Comment (simonpasquier) [inline pkg/rules/rulespb/custom.go:195]: is this relevant?

Comment (s-urbaniak) [reply pkg/rules/rulespb/custom.go:195]: no it is a copy-paste error, good catch!

**Comment by s-urbaniak** [comment]
I am not sure why this fails :thinking: 
```
make: *** [Makefile:208: test] Terminated

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by s-urbaniak** [comment]
ha, somebody was faster, let me rebase on the newest changelog ;-)
