### PR TITLE
Query Frontend splitting metrics check is flaky

### LINKED ISSUE #6951: Query Frontend splitting metrics check is flaky
**What happened**:

https://github.com/thanos-io/thanos/actions/runs/7066224273/job/19237709120?pr=6950 Query Frontend E2E tests failed again due to the splitting metrics. It is a very old flaky issue but it is not fixed.

The problem is that the time splitting feature in QFE is based on the absolute time of the timestamp, not based on the query time range. For example, even if a range query is only 2h time range, it can still be split into 2 queries if it is at the boundary of the split interval. If interval is 24h, [yesterday 23PM, today 1AM] range query will become two range queries. This caused our E2E tests to fail.

To fix this, a good way is to not use time.Now() as the timestamp we used to query metrics. By using absolute timestamps, we can control the request parameters and make sure time splitting works as expected.

However, the chanllenge is that we use Prometheus to scrape metrics in E2E tests and the metric timestamp is latest (now). So we have to use latest timestamps in QFE query rather than arbitrary timestamps.

We can probably refactor the QFE E2E tests to not use Prometheus, but use Thanos Receivers instead. Metrics can be sent via remote write requests with predefined timestamps. This way we can use the timestamp we pick to query metrics

### PR DESCRIPTION
**Pull request by pawarpranav83**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Fixes #6951, by using receiver instead of prometheus instance.

### CODE REVIEW

**Comment by pawarpranav83** [comment]
@yeya24 , for the store tests, what is the directory string that I should specify, there is one instance, where they use e.ShareDir()/tmp, but when used this, I don't think receiver can access data from there, is there some additional config for this?
https://github.com/thanos-io/thanos/blob/d388b7403ddc87eda29a51ad8577a33880bc6b87/test/e2e/query_frontend_test.go#L601

**Comment by yeya24** [comment]
@pawarpranav83 You can just go ahead and change this code to use remote write to ingest data instead. It should be the same as creating the block directly

File: test/e2e/query_frontend_test.go [hunk 1]
```diff
@@ -717,18 +732,18 @@ func TestRangeQueryDynamicHorizontalSharding(t *testing.T) {
...
 	testutil.Ok(t, queryFrontend.WaitSumMetrics(e2emon.Equals(2), "querier_cache_added_new_total"))
-	testutil.Ok(t, queryFrontend.WaitSumMetrics(e2emon.Equals(3), "querier_cache_added_total"))
-	testutil.Ok(t, queryFrontend.WaitSumMetrics(e2emon.Equals(3), "querier_cache_misses_total"))
+	testutil.Ok(t, queryFrontend.WaitSumMetrics(e2emon.Equals(4), "querier_cache_added_total"))
+	testutil.Ok(t, queryFrontend.WaitSumMetrics(e2emon.Equals(4), "querier_cache_misses_total"))
 
 	// Query interval is 2 hours, which is greater than min-slit-interval, query will be broken down into 4 parts
-	// + rest (of interval)
-	testutil.Ok(t, queryFrontend.WaitSumMetrics(e2emon.Equals(5), "thanos_frontend_split_queries_total"))
+	// + rest (of interval) - Doubt - what is rest of interval?
```
Comment (yeya24) [inline test/e2e/query_frontend_test.go:742]: There is no rest of interval since the specified timestamp is a multiple of `MinQuerySplitInterval` which is one hour.
Let's clean up this.

File: test/e2e/query_frontend_test.go [hunk 2]
```diff
@@ -717,18 +732,18 @@ func TestRangeQueryDynamicHorizontalSharding(t *testing.T) {
...
+	testutil.Ok(t, queryFrontend.WaitSumMetrics(e2emon.Equals(4), "thanos_frontend_split_queries_total"))
 
 	testutil.Ok(t, querier.WaitSumMetricsWithOptions(
-		e2emon.Equals(5),
+		e2emon.Equals(4), // Doubt
```
Comment (yeya24) [inline test/e2e/query_frontend_test.go:746]: It is unnecessary to mention doubt in the code comment. You can just leave commets directly via Github comments

Comment (pawarpranav83) [reply test/e2e/query_frontend_test.go:746]: right :)

**Comment by pawarpranav83** [comment]
ok, so only one query is failing - 

```
{
        name:           "binary expression",
        qryFunc:        func() string { return `http_requests_total{pod="1"} / http_requests_total` },
        expectedSeries: 2,
},
```

https://github.com/pawarpranav83/thanos/blob/8889222e610f032889bcb555385c7a60c1b38577/test/e2e/query_frontend_test.go#L872-L876

How do we solve this?

File: test/e2e/query_frontend_test.go [hunk 3]
```diff
@@ -596,14 +595,36 @@ func TestRangeQueryShardingWithRandomData(t *testing.T) {
...
+				Name:  string(label.Name),
+				Value: string(label.Value),
+			})
+		}
+		samplespb = append(samplespb, prompb.TimeSeries{
+			Labels: labelspb,
+			Samples: []prompb.Sample{
+				{
+					Value:     float64(0),
+					Timestamp: timestamp.FromTime(predefTimestamp.Time()),
```
Comment (pawarpranav83) [inline test/e2e/query_frontend_test.go:619]: For the Timestamp of samples, should I have different timestamps from start to end, increment with step size (its implemented like that in CreateBlock function), it worked for the range query but not for instant query in the other test func, so should I add that?

**Comment by MichaHoffmann** [comment]
> ok, so only one query is failing -
> 
> ```
> {
>         name:           "binary expression",
>         qryFunc:        func() string { return `http_requests_total{pod="1"} / http_requests_total` },
>         expectedSeries: 2,
> },
> ```
> 
> https://github.com/pawarpranav83/thanos/blob/8889222e610f032889bcb555385c7a60c1b38577/test/e2e/query_frontend_test.go#L872-L876
> 
> How do we solve this?

just a guess, but can you try sorting the results before comparing? Can you print the results too please, im curious what is different!

File: test/e2e/query_frontend_test.go (hunk 3 above)
Comment (MichaHoffmann) [reply test/e2e/query_frontend_test.go:619]: I think it doesnt matter for instant query, i might be wrong though!

**Comment by pawarpranav83** [comment]
It was the sample value since it was 0, it was giving NaN, when changed to 1, it worked :)
So changing it in all tests now.

**Comment by pawarpranav83** [comment]
And on a completely unrelated topic, do u know any talks that explain the working of the store gateway (mainly the caching system), I couldn't find any so...

**Comment by MichaHoffmann** [comment]
> It was the sample value since it was 0, it was giving NaN, when changed to 1, it worked :)

Good catch!

**Comment by pawarpranav83** [comment]
re-run test?
And are there any more corrections / changes to be done?

**Review by yeya24 — APPROVED** [review]
Thanks!
