### PR TITLE
Fix the metadata API flaky tests

### LINKED ISSUE #4012: Flaky test case metadata API fanout
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

**What happened**:

https://github.com/thanos-io/thanos/pull/4010/checks?check_run_id=2249690066#step:5:1828

Because the output string is too long, the error message is truncated so it is hard to know what's the diff.

**What you expected to happen**:

The result from Prometheus metadata API and Thanos querier metadata API should be the same.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

Fixes #4012

## Changes

Refactor the metadata E2E test and use `metadataEqual` function to compare the two responses instead of just using reflect.DeepEqual.

In `metadataEqual` function, each entry in the metadata response is first sorted and then compare. This fixes the problem mentioned in https://github.com/thanos-io/thanos/issues/4012#issuecomment-812542755

Update: I also rewrite the unit tests of metadata API.

### CODE REVIEW

File: test/e2e/metadata_api_test.go [hunk 1]
```diff
@@ -95,3 +100,23 @@ func TestMetadataAPI_Fanout(t *testing.T) {
...
+
+func metadataEqual(t *testing.T, meta1, meta2 map[string][]metadatapb.Meta) {
+	// The two responses should have equal # of entries.
+	testutil.Equals(t, len(meta1), len(meta2))
+
+	for metric := range meta1 {
+		// Get metadata for the metric.
+		meta1MetricMeta := meta1[metric]
+		meta2MetricMeta, ok := meta2[metric]
+		testutil.Assert(t, true, ok)
```
Comment (onprem) [inline test/e2e/metadata_api_test.go:112]: Just confirming. Don't we need to check `ok` for `meta1MetricMeta` as well?

File: test/e2e/metadata_api_test.go [hunk 2]
```diff
@@ -95,3 +100,23 @@ func TestMetadataAPI_Fanout(t *testing.T) {
...
+
+		sort.Slice(meta1MetricMeta, func(i, j int) bool {
+			return meta1MetricMeta[i].Help < meta1MetricMeta[j].Help
+		})
+		sort.Slice(meta2MetricMeta, func(i, j int) bool {
+			return meta2MetricMeta[i].Help < meta2MetricMeta[j].Help
+		})
+		reflect.DeepEqual(meta1MetricMeta, meta2MetricMeta)
```
Comment (onprem) [inline test/e2e/metadata_api_test.go:120]:
```suggestion
		testutil.Assert(t, true, reflect.DeepEqual(meta1MetricMeta, meta2MetricMeta))
```

File: test/e2e/metadata_api_test.go (hunk 1 above)
Comment (yeya24) [reply test/e2e/metadata_api_test.go:112]: We are iterating meta1 now

Comment (yeya24) [reply test/e2e/metadata_api_test.go:112]: We are iterating meta1 now

File: test/e2e/metadata_api_test.go (hunk 2 above)
Comment (yeya24) [reply test/e2e/metadata_api_test.go]: Thanks for catching this!

File: test/e2e/metadata_api_test.go [hunk 3]
```diff
@@ -66,32 +71,63 @@ func TestMetadataAPI_Fanout(t *testing.T) {
 	testutil.Ok(t, q.WaitSumMetricsWithOptions(e2e.Equals(2), []string{"thanos_store_nodes_grpc_connections"}, e2e.WaitMissingMetrics))
 	testutil.Ok(t, q.WaitSumMetricsWithOptions(e2e.Equals(2), []string{"thanos_query_metadata_apis_dns_provider_results"}, e2e.WaitMissingMetrics))
 
-	promMeta, err := promclient.NewDefaultClient().MetadataInGRPC(ctx, mustURLParse(t, "http://"+prom1.HTTPEndpoint()), "", -1)
-	testutil.Ok(t, err)
+	var (
```
Comment (bwplotka) [inline test/e2e/metadata_api_test.go:74]: for single variable we could just inline `var` (:

**Review by bwplotka — COMMENTED** [review]
Awesome, thank you for fixing this @yeya24 ! 🤗 Some suggestions

File: pkg/metadata/prometheus_test.go [hunk 4]
```diff
@@ -36,17 +41,58 @@ scrape_configs:
...
+
+	// Do a hot reload for loading the latest configuration.
+	err = p.Reload()
+	testutil.Ok(t, err)
 
 	u, err := url.Parse("http://" + p.Addr())
 	testutil.Ok(t, err)
 
-	prom := NewPrometheus(u, promclient.NewDefaultClient())
+	c := promclient.NewClient(http.DefaultClient, logger, "")
```
[the remark this answers is not in the document]
Comment (yeya24) [reply pkg/metadata/prometheus_test.go:82]: It is used in `meta, err := c.MetadataInGRPC(ctx, u, "", -1)`.

File: pkg/metadata/prometheus_test.go [hunk 5]
```diff
@@ -36,17 +41,58 @@ scrape_configs:
...
+  external_labels:
+    region: eu-west
+scrape_configs:
+- job_name: 'myself'
+  # Quick scrapes for test purposes.
+  scrape_interval: 1s
+  scrape_timeout: 1s
+  static_configs:
+  - targets: ['%s']
+`, p.Addr()))
```
[the remark this answers is not in the document]
Comment (yeya24) [reply pkg/metadata/prometheus_test.go:72]: We can define one target called `PROMETHEUS_ADDRESS` to let the Prometheus start function know that this target should be replaced by the current Prometheus address.
WDYT?

File: pkg/metadata/prometheus_test.go [hunk 6]
```diff
@@ -36,17 +41,58 @@ scrape_configs:
...
   static_configs:
-  - targets: ['localhost:9090','localhost:80']
+  - targets: ['localhost:9090']
 `))
 	testutil.Ok(t, p.Start())
 
-	time.Sleep(10 * time.Second)
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+	_ = ctx
```
[the remark this answers is not in the document]
Comment (yeya24) [reply pkg/metadata/prometheus_test.go:50]: Sorry, I forgot removing this.

File: pkg/metadata/prometheus_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (yeya24) [reply pkg/metadata/prometheus_test.go]: Fixed in https://github.com/thanos-io/thanos/pull/4013/commits/0c3211c74c0c6e55c0aa175b80a1bf5d3869e782.

File: pkg/metadata/prometheus_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (GiedriusS) [reply pkg/metadata/prometheus_test.go:60]: I think what @bwplotka meant is that we only use it in one place so it can be in-lined but I'd argue that it's more readable the way it is right now because you do not have a chain of function calls with quite a few arguments

[the remark this answers is not in the document]
Comment (GiedriusS) [reply pkg/metadata/prometheus_test.go:60]: Not just that but also `grpcClient := NewGRPCClient(NewPrometheus(u, c))` so it makes sense so leave this as is. Plus, it's more readable to have it this way instead of chaining function calls with quite a few parameters.

File: test/e2e/metadata_api_test.go (hunk 3 above)
Comment (GiedriusS) [reply test/e2e/metadata_api_test.go:74]: Forgot this @yeya24 ? :P

File: test/e2e/metadata_api_test.go [hunk 7]
```diff
@@ -66,32 +71,63 @@ func TestMetadataAPI_Fanout(t *testing.T) {
...
 
 	// Metadata response from Prometheus and Thanos Querier should be the same after deduplication.
-	testutil.Equals(t, thanosMeta, promMeta)
+	metadataEqual(t, thanosMeta, promMeta)
 
 	// We only expect to see one metadata returned.
 	thanosMeta, err = promclient.NewDefaultClient().MetadataInGRPC(ctx, mustURLParse(t, "http://"+q.HTTPEndpoint()), "", 1)
 	testutil.Ok(t, err)
-	testutil.Assert(t, true, len(thanosMeta) == 1)
+	testutil.Assert(t, len(thanosMeta) == 1, "expected 1 metadata from Thanos, got %d", len(thanosMeta))
```
Comment (GiedriusS) [inline test/e2e/metadata_api_test.go:97]: What's the reasoning behind these? Why not just `testutil.Equals(t, len(thanosMeta), 1)` and that's it? :P

**Review by GiedriusS — COMMENTED** [review]
LGTM, just I think you forgot one comment. And I have a question as well

File: test/e2e/metadata_api_test.go (hunk 7 above)
Comment (yeya24) [reply test/e2e/metadata_api_test.go:97]: Umm, that' so true! :p I will update it.

**Comment by yeya24** [comment]
Hi @GiedriusS. I have updated my pr. Please take a look, thank you.

**Review by GiedriusS — APPROVED** [review]
LGTM. Does the Prometheus target stuff look good to you now, @bwplotka? :P It looks nice to me

**Review by bwplotka — APPROVED** [review]
Yes, LGTM. Thanks all! 🚀
