### PR TITLE
Rule: Fix URI encoding of strings

### LINKED ISSUE #7002: Rule: upgrade to v0.33.0: error in thanos url template
**Thanos, Prometheus and Golang version used**:
thanos v0.33.0

**What happened**:
Upgrading from v0.32 to v0.33.0, the thanos url advertised by our ruler cannot be opened back in thanos query anymore.
I think this is due to https://github.com/thanos-io/thanos/pull/6308

**What you expected to happen**:
Thanos urls to be clickable as before

**How to reproduce it (as minimally and precisely as possible)**:
We have not changed anything so it is using the default:
`--alert.query-template="/graph?g0.expr={{.Expr}}&g0.tab=1"`

**Anything else we need to know**:
I think this is due to some html encoding of spaces:
we are seeing urls like: 
`https://<redacted>/graph?g0.expr=%28max&#43;by&#43;%28namespace%2C&#43;pod%2C&#43;instance%2C&#43;container%29&#43;%28increase%28kube_pod_container_status_restarts_total%7Bnamespace%21~%22openshift-gitops%7Copenshift-marketplace%7Copenshift-pipelines%22%2Cprometheus%3D%22platform%22%7D%5B1h%5D%29%29&#43;%3E%3D&#43;4%29&g0.tab=1`

url decode:
Screenshot 2023-12-21 at 15 49 08

When clicking on it, thanos query, opens it with:
Screenshot 2023-12-21 at 15 51 05

`https://<redacted>/graph?g0.expr=%20(max&g0.tab=1&g0.stacked=0&g0.range_input=1h&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D&g0.engine=thanos&g0.analyze=0`

### PR DESCRIPTION
**Pull request by kartikaysaxena**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Should fix #7002
Added how the URI should treat `+` as it is ignored by `url.QueryEscape`

[Reference](https://forum.golangbridge.org/t/html-template-may-invalidate-urls-encoded-using-url-queryescape/4219)

### CODE REVIEW

**Review by MichaHoffmann — COMMENTED** [review]
Can you add a test in `Test_tableLinkForExpression` please? but to be honest: i dont understand it; the URL seems valid on its own ( not in a html context ); is this maybe an issue of whatever renders the notification in the end?

**Comment by MichaHoffmann** [comment]
Ah i understand now; spaces are encoded as `+` by the stdlib (https://github.com/golang/go/issues/4013) and the html/template package then escapes that again to `&#43`. I wonder wouldnt it be easier to not render the URL as html but just use "text/template"? That way we are sure we are not replacing anything else too. ( POC playground: https://go.dev/play/p/Jpl3iCbtQLR )

**Comment by kartikaysaxena** [comment]
Sure! Will do implement this.

File: cmd/thanos/rule.go [hunk 1]
```diff
@@ -7,7 +7,7 @@ import (
 	"bytes"
 	"context"
 	"fmt"
-	"html/template"
+	"text/template"
```
Comment (MichaHoffmann) [inline cmd/thanos/rule.go:10]: I'm not sure if we also should change the other usages of "template"; i would prefer if we had "texttemplate" and "htmltemplate" and only changed the one invocation where html is problematic ( the url expression ).

**Review by MichaHoffmann — COMMENTED** [review]
LGTM, can you squash commits please?

**Review by yeya24 — APPROVED** [review]
Thanks. Can we update changelog?

**Review by MichaHoffmann — APPROVED** [review]
LGTM
