### PR TITLE
*: Handle SIGHUP

### LINKED ISSUE #1333: Handle SIGHUP event
**Thanos, Prometheus and Golang version used**

thanos: v0.5.0

**What happened**

Sending a SIGHUP signal to sidecar, store gateway, querier or compactor crashes it.

**What you expected to happen**

They should not crash. Maybe they should also reload configuration (?)

**How to reproduce it (as minimally and precisely as possible)**:

```sh
$ kill -SIGHUP <thanos>
```

I think thanos should at least not crash upon receiving a SIGHUP signal.

I understand that flags are used to configure thanos components, but it would be nice to have a way to reload configuration files immediately with a SIGHUP signal. This is what most applications do (eg: prometheus). Potential use case: Have an ansible handler sending the SIGHUP signal.

### PR DESCRIPTION
**Pull request by kakkoyun**
This PR handles received SIGHUP signals and dispatches reload events to sub-commands to handle.
Only the ruler utilizes this right now. Receiver and Ruler implement their own file watchers to reload configurations.

Fixes #1333.

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Verification

* `make test-local`
* MINIO_ENABLED=1 ./scripts/quickstart.sh
  - `kill -HUP <thanos-pid>`

### CODE REVIEW

File: cmd/thanos/main.go [hunk 1]
```diff
@@ -178,7 +178,9 @@ func main() {
 		})
 	}
 
-	if err := cmds[cmd](&g, logger, metrics, tracer, *logLevel == "debug"); err != nil {
+	reloadCh := make(chan struct{})
```
Comment (kakkoyun) [inline cmd/thanos/main.go]: This should be a buffered channel with a capacity of 1. Will fix it.

File: cmd/thanos/main.go [hunk 2]
```diff
@@ -211,3 +224,21 @@ func interrupt(logger log.Logger, cancel <-chan struct{}) error {
...
+
+func reload(logger log.Logger, cancel <-chan struct{}, r chan<- struct{}) error {
+	c := make(chan os.Signal, 1)
+	signal.Notify(c, syscall.SIGHUP)
+	for {
+		select {
+		case s := <-c:
+			level.Info(logger).Log("msg", "caught signal. Reloading.", "signal", s)
+			select {
+			case r <- struct{}{}:
```
Comment (bwplotka) [inline cmd/thanos/main.go]: What if no one is receiving here?

Comment (bwplotka) [reply cmd/thanos/main.go]: I think we mind this 
```
{
		cancel := make(chan struct{})
		g.Add(func() error {
			return reload(logger, cancel, reloadCh)
		}, func(error) {
			close(cancel)
		})
	}
```
To be per command maybe? Or noop otherwise? That's the reason and also we might think of redesigning commands and the number of arguments is becoming a problem (:

Comment (kakkoyun) [reply cmd/thanos/main.go]: > What if no one is receiving here?

When no one is receiving that means (or if someone's receiving), we just allocate 4 bytes of memory for the full lifecycle of the program. It's unnecessary if no one receiving of course. Empty structs allocate zero bytes of memory, fortunately. (so allocation is just for the channel)
https://play.golang.org/p/2QPjVBQZSGU

That being said I'll have another look at it to avoid unnecessary allocation.

> To be per command maybe? Or noop otherwise? 

I will have another look at this, find a clean way to achieve it.
I just don't want to handle signals outside the `main.go`, it makes things harder to pinpoint.

> That's the reason and also we might think of redesigning commands and the number of arguments is becoming a problem (:

Yes, we definitely need to find more elegant solution to this parameter problem. As once a great man said:

> “If you have a procedure with 10 parameters, you probably missed some.”
> —Allan Perlis

🤪

Comment (bwplotka) [reply cmd/thanos/main.go]: > When no one is receiving that means (or if someone's receiving), we just allocate 4 bytes of memory for the full lifecycle of the program

I don't think only 4 bytes. I am more worried on signal channel.Whatt if no one is receiving and I will send 100mln of SIGHUP signals?

Comment (bwplotka) [reply cmd/thanos/main.go]: For redesign we probably need to finally move to some structure (: I remember Cortex had some quite nice modules structure.. worth to get inspired? Cc @gouthamve

Comment (kakkoyun) [reply cmd/thanos/main.go]: > Whatt if no one is receiving and I will send 100mln of SIGHUP signals?
That’s why it’s in an additional select with default case so that it can just continue on if the buffered (reload) channel is full. So memory will always be constant, it’ll just loop over 100mln.

Comment (bwplotka) [reply cmd/thanos/main.go]: You are right, I missed this default case. Thanks! ((:

**Comment by kakkoyun** [comment]
@bwplotka Should I move handling logic per subcommand? or is this good enough?
