### PR TITLE
bucket: "inspect --sort-by" doesn't work in all cases

### LINKED ISSUE #2414: bucket: "inspect --sort-by" is not numeric-aware
**Thanos, Prometheus and Golang version used**: v0.11.0

**What happened**: `bucket inspect --sort-by UNTIL-DOWN` does not produce expected ordering

**What you expected to happen**: sort numerically by time duration

If it's too complex to support alpha vs. numeric, sorting direction, etc. perhaps it would be better to remove the `--sort-by` feature and leave it to post-processing...

**How to reproduce it (as minimally and precisely as possible)**:
```
$ /bin/thanos bucket inspect --sort-by UNTIL-DOWN
|            ULID            |        FROM         |        UNTIL        |  RANGE   | UNTIL-DOWN |  #SERIES  |    #SAMPLES    |  #CHUNKS   | COMP-LEVEL | COMP-FAILED |    LABELS    | RESOLUTION |  SOURCE   |
|----------------------------|---------------------|---------------------|----------|------------|-----------|----------------|------------|------------|-------------|--------------|------------|-----------|
...
| 01E5096G1P88MBXNATDFDPNNRG | 01-04-2020 06:00:00 | 03-04-2020 12:00:00 | 54h0m0s  | -14h0m0s   | 2,316,976 | 3,964,484,856  | 37,540,413 | 4          | false       | replica=main | 0s         | sidecar   |
| 01E5H7MQCQ5Q86095CC1JSJ8AV | 26-12-2019 12:00:00 | 04-01-2020 12:00:00 | 216h0m0s | -176h0m0s  | 842,250   | 1,978,856,089  | 19,461,079 | 6          | false       | replica=main | 0s         | compactor |
| 01E5H6MFM2A9QSMCSX2JK441T8 | 08-04-2020 00:00:00 | 10-04-2020 00:00:00 | 48h0m0s  | -8h0m0s    | 2,207,280 | 3,711,359,114  | 34,641,807 | 3          | false       | replica=main | 0s         | compactor |
| 01E5HCVWQSC1492701AWVKM0CF | 09-03-2020 18:00:00 | 12-03-2020 00:00:00 | 54h0m0s  | 186h0m0s   | 1,880,277 | 580,895,412    | 5,115,790  | 4          | true        | replica=main | 5m0s       | compactor |
| 01E5HHR9V8NGYBC7CTAVYX766E | 27-03-2020 18:00:00 | 30-03-2020 00:00:00 | 54h0m0s  | 186h0m0s   | 1,688,583 | 701,582,637    | 5,788,266  | 4          | true        | replica=main | 5m0s       | compactor |
| 01E5HJTRFBPC2PG44J5BQA170R | 05-03-2020 06:00:00 | 07-03-2020 12:00:00 | 54h0m0s  | 186h0m0s   | 1,795,213 | 572,997,620    | 5,012,678  | 4          | true        | replica=main | 5m0s       | compactor |
| 01E5HQACS5J0RGANE2D9H40W2V | 30-03-2020 00:00:00 | 01-04-2020 06:00:00 | 54h0m0s  | 186h0m0s   | 2,201,667 | 786,975,870    | 6,748,038  | 4          | true        | replica=main | 5m0s       | compactor |
| 01E5HS781NM79E3CT9PBN7GKPR | 01-04-2020 06:00:00 | 03-04-2020 12:00:00 | 54h0m0s  | 186h0m0s   | 2,316,976 | 805,786,196    | 6,953,904  | 4          | false       | replica=main | 5m0s       | compactor |
| 01E5J1HHD53XG3TC3V6NWAEJ8W | 25-03-2020 12:00:00 | 27-03-2020 18:00:00 | 54h0m0s  | 186h0m0s   | 2,031,452 | 716,804,692    | 6,159,897  | 4          | true        | replica=main | 5m0s       | compactor |
| 01E5J4SN7PHQW6Z2WQ3DAZC3Y7 | 07-03-2020 12:00:00 | 09-03-2020 18:00:00 | 54h0m0s  | 186h0m0s   | 1,696,303 | 562,270,851    | 4,858,224  | 4          | true        | replica=main | 5m0s       | compactor |
| 01E5HDVZSCJNRGWJ301YTG4FKT | 08-04-2020 00:00:00 | 10-04-2020 00:00:00 | 48h0m0s  | 192h0m0s   | 2,207,280 | 755,607,249    | 6,784,993  | 3          | false       | replica=main | 5m0s       | compactor |
| 01E526VK93N0JRPNZPR5Y4TNC7 | 03-04-2020 12:00:00 | 04-04-2020 06:00:00 | 18h0m0s  | 22h0m0s    | 1,670,889 | 1,309,978,265  | 11,885,519 | 3          | false       | replica=main | 0s         | sidecar   |
| 01E544MJZP1HD9NCB2YS6SWRKJ | 04-04-2020 06:00:00 | 05-04-2020 00:00:00 | 18h0m0s  | 22h0m0s    | 1,571,817 | 1,250,676,619  | 11,341,306 | 3          | false       | replica=main | 0s         | sidecar   |
...
```

### PR DESCRIPTION
**Pull request by kadern0**
Fixes #2414 
The compare function used for sorting only checks if the string is `Time` type which causes wrong sorting if the string is `TimeDuration` type.

* [x] I added CHANGELOG entry for this change.
* [X] Change is not relevant to the end user.

## Changes

Added extra check to compare `time Duration` type values.

## Verification

Manually tested the compare function with different type of strings

### CODE REVIEW

File: cmd/thanos/bucket.go [hunk 1]
```diff
@@ -582,10 +582,21 @@ func (t Table) Less(i, j int) bool {
 }
 
 func compare(s1, s2 string) bool {
+	// Values can be either Time, Duration or other.
```
Comment (belm0) [inline cmd/thanos/bucket.go:585]: comma-delimited integer also needs to be handled, for `#SAMPLES`, etc.

see https://github.com/thanos-io/thanos/issues/2414#issuecomment-612554861

**Comment by belm0** [comment]
```
>  [ ] I added CHANGELOG entry for this change.
>  [X] Change is not relevant to the end user.
```

Perhaps worth a CHANGELOG entry?

**Comment by kadern0** [comment]
@belm0 thank you very much for all your comments! I'm more than happy to add a CHANGELOG entry for this as it is a (non-critical) bug fix.

File: cmd/thanos/bucket.go (hunk 1 above)
Comment (kadern0) [reply cmd/thanos/bucket.go:585]: This was my initial comment where I thought there were only 3 different possible  string 'types', it was only a reminder. I can update it or remove it, what do you think?

File: cmd/thanos/bucket.go [hunk 2]
```diff
@@ -582,10 +582,21 @@ func (t Table) Less(i, j int) bool {
...
 	if s1Err != nil || s2Err != nil {
-		return s1 < s2
+		s1Duration, s1Err := time.ParseDuration(s1)
+		s2Duration, s2Err := time.ParseDuration(s2)
+		if s1Err != nil || s2Err != nil {
+			s1Int, s1Err := strconv.Atoi(strings.Replace(s1, ",", "", -1))
+			s2Int, s2Err := strconv.Atoi(strings.Replace(s2, ",", "", -1))
+			if s1Err != nil || s2Err != nil {
+				return s1 < s2
+			}
```
[the remark this answers is not in the document]
Comment (kadern0) [reply cmd/thanos/bucket.go:596]: This part you are highlighting here is the part that handles the integers strings with thousand commas inside them. 
The workflow of the function is:
-> check if strings are timestamps -> check if strings are duration -> check if strings are integers -> just compare regular strings 

This should cover all the cases mentioned in the issue.

File: cmd/thanos/bucket.go (hunk 1 above)
Comment (kadern0) [reply cmd/thanos/bucket.go:585]: I mean, they are being handled despite of not being specified in the comment

File: cmd/thanos/bucket.go [hunk 3]
```diff
@@ -582,10 +582,21 @@ func (t Table) Less(i, j int) bool {
...
 func compare(s1, s2 string) bool {
+	// Values can be either Time, Duration or other.
 	s1Time, s1Err := time.Parse("02-01-2006 15:04:05", s1)
 	s2Time, s2Err := time.Parse("02-01-2006 15:04:05", s2)
 	if s1Err != nil || s2Err != nil {
-		return s1 < s2
+		s1Duration, s1Err := time.ParseDuration(s1)
+		s2Duration, s2Err := time.ParseDuration(s2)
+		if s1Err != nil || s2Err != nil {
+			s1Int, s1Err := strconv.Atoi(strings.Replace(s1, ",", "", -1))
```
Comment (GiedriusS) [inline cmd/thanos/bucket.go:592]: This will run into problems once that string won't fit into an `int`. We should opt to use:
```
strconv.ParseUint(strings.Replace(s1, ",", "", -1), 10, 64)
```
Which will give us an `uint64`. This is a real possibility because we use `uint64` underneath on:
* `blockMeta.Stats.NumSeries`
* `blockMeta.Stats.NumSamples`
* `blockMeta.Stats.NumChunks`

File: cmd/thanos/bucket.go (hunk 1 above)
Comment (GiedriusS) [reply cmd/thanos/bucket.go:585]: We could update this comment to fit the reality.

File: cmd/thanos/bucket.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (belm0) [reply cmd/thanos/bucket.go:596]: I see-- I misread the code.

For readability, may I suggest adding a comment with a value example above each parsing call?

```golang
// try parsing as datetime
s1Time, s1Err := time.Parse("02-01-2006 15:04:05", s1)
...
// try parsing as duration, e.g.  "-1h10m5s"
s1Duration, s1Err := time.ParseDuration(s1)
...
// try parsing as comma-delimited int, e.g. "3,964,484,856"
s2Int, s2Err := strconv.Atoi(strings.Replace(s2, ",", "", -1))
```

**Comment by kadern0** [comment]
Thank you for your help @GiedriusS and @belm0

File: CHANGELOG.md [hunk 4]
```diff
@@ -12,7 +12,7 @@ We use *breaking* word for marking changes that are not backward compatible (rel
 ## Unreleased
 
 ### Fixed
-
```
Comment (bwplotka) [inline CHANGELOG.md:15]: Eh @squat all of those would so tricky to merge with release branch ):

**Comment by bwplotka** [comment]
Thanks!
