### PR TITLE
mixin: Reintroduce thanos_objstore_bucket_operation_failures_total alert

### LINKED ISSUE #3005: Alert missing for bucket operation failures on the sidecar
**Thanos, Prometheus and Golang version used**:
quay.io/prometheus/prometheus:v2.20.0
quay.io/thanos/thanos:v0.14.0

**Object Storage Provider**:
Scaleway S3 compatible object store

**What happened**:
The sidecar was failing to upload to the S3 (my fault) but no alerts were triggered.

**What you expected to happen**:
An alert to be triggered.

**How to reproduce it (as minimally and precisely as possible)**:
Set up a network policy that blocks uploading

**Full logs to relevant components**:
```
level=warn ts=2020-08-08T11:50:28.85471248Z caller=sidecar.go:285 err="check exists: stat s3 object: Get \"https://s3.nl-ams.scw.cloud/<bucket-name>/?location=<location>": dial tcp 163.172.208.8:443: connect: connection refused" uploaded=0
```

**Anything else we need to know**:
It looks like this used to work by having an alert on `thanos_objstore_bucket_operation_failures_total`. I actually found the issue when I looked at the thanos sidecar dashboard.

It looks like #2002 removed the alert. I think only ones with `_s3_`/`_gcs_` in the name were meant to be removed?

### PR DESCRIPTION
**Pull request by MalloZup**
## Description:

Metric was removed on PR 2002 accidentally. fix #3005 

* [ ] I added CHANGELOG entry for this change.

## Changes

- reintroduce alert `thanos_objstore_bucket_operation_failures_total` which was deleted by mistake

## Verification

tested with make example-rules-lint

### CODE REVIEW

**Comment by yeya24** [comment]
Hi, please add this alert to the jsonnet file https://github.com/thanos-io/thanos/blob/master/mixin/alerts/sidecar.libsonnet. 
The markdown files can be auto-generated I think.

**Comment by MalloZup** [comment]
@yeya24 thx. I added the jsonnet and generated the markdown via makefile targets. Let me know if something else is missing.

Btw I removed the runbook.md in case is needed I will readd it

**Comment by MalloZup** [comment]
I see unit-test are failing I will take look on this.

**Comment by yeya24** [comment]
> I see unit-test are failing I will take look on this.

That's not related to this pr so all good.

File: pkg/rules/rules_test.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func testRulesAgainstExamples(t *testing.T, dir string, server rulespb.RulesServ
 		{
 			Name:                    "thanos-sidecar",
 			File:                    filepath.Join(dir, "alerts.yaml"),
-			Rules:                   []*rulespb.Rule{someAlert, someAlert},
+			Rules:                   []*rulespb.Rule{someAlert, someAlert, someAlert},
```
Comment (MalloZup) [inline pkg/rules/rules_test.go:85]: @yeya24  I have added this `someAlert` fixtures. I was thinking this is needed here since we are adding an alert to the libsonet.

Comment (yeya24) [reply pkg/rules/rules_test.go:85]: I am not sure. Maybe @kakkoyun or @metalmatze would like to take a look?

Comment (yeya24) [reply pkg/rules/rules_test.go:85]: Ah yes. Sorry for the late reply. I just checked it again and I think this change is needed. Thanks!

**Comment by yeya24** [comment]
CC @kakkoyun or @metalmatze for a review ^^

File: mixin/alerts/sidecar.libsonnet [hunk 2]
```diff
@@ -22,6 +22,20 @@
...
             },
           },
+          {
+            alert: 'ThanosSidecarBucketOperationsFailed',
+            annotations: {
+              description: 'Thanos Sidecar {{$labels.job}} {{$labels.pod}} bucket operations are failing',
+              summary: 'Thanos Sidecar cannot connect to Prometheus',
+            },
+            expr: |||
+              rate(thanos_objstore_bucket_operation_failures_total{name="prometheus"}[5m]) > 0
```
Comment (kakkoyun) [inline mixin/alerts/sidecar.libsonnet:32]:
```suggestion
              rate(thanos_objstore_bucket_operation_failures_total{name="prometheus"}[5m]) > 0
```
Selectors should be templated, check out the other alert examples.

**Review by kakkoyun — CHANGES_REQUESTED** [review]
Looking good. Thanks for your contribution. Only one comment.

File: mixin/alerts/sidecar.libsonnet (hunk 2 above)
Comment (MalloZup) [reply mixin/alerts/sidecar.libsonnet]: right done

File: pkg/rules/rules_test.go (hunk 1 above)
Comment (MalloZup) [reply pkg/rules/rules_test.go:85]: ok thx!

File: mixin/alerts/sidecar.libsonnet (hunk 2 above)
Comment (kakkoyun) [reply mixin/alerts/sidecar.libsonnet]: AFAIT from the CI failures you need to run `make examples`

Comment (MalloZup) [reply mixin/alerts/sidecar.libsonnet]: ah thx!

Comment (MalloZup) [reply mixin/alerts/sidecar.libsonnet]: should be done

**Comment by MalloZup** [comment]
@yeya24 @kakkoyun thank you for your reviews. I have fixed your kind comments.

Let me know if other things are missing. Otherwise I will look to a next issue to contribute on :dog2: :service_dog:

File: examples/alerts/alerts.yaml [hunk 3]
```diff
@@ -295,6 +295,17 @@ groups:
     for: 5m
     labels:
       severity: critical
+  - alert: ThanosSidecarBucketOperationsFailed
+    annotations:
+      description: Thanos Sidecar {{$labels.job}} {{$labels.pod}} bucket operations
+        are failing
+      runbook_url: https://github.com/thanos-io/thanos/tree/master/mixin/runbook.md#alert-name-thanossidecarbucketoperationsfailed
+      summary: Thanos Sidecar cannot connect to Prometheus
```
Comment (yeya24) [inline examples/alerts/alerts.yaml:303]: @MalloZup Sorry I missed this. Can you update the summary?

**Review by yeya24 — CHANGES_REQUESTED** [review]

**Review by kakkoyun — APPROVED** [review]
LGTM 🚀 Thanks for the contribution.

**Comment by kakkoyun** [comment]
@yeya24 Feel free to merge it if it's also looking good to you.

**Comment by MalloZup** [comment]
thx guys for patience and help for getting through this.  :sunflower: 
 I have learned the `mixin` concept of prometheus/grafana, which I wasn't quite aware, so I did definitely discovered something new by this PR :poodle:  

And also jsonnet, was not familiar with it. I knew dhall and toml but  not yet jsonnet. :grin:  That is definitely something I enjoy when picking up new issue on unfamiliar environment .. Thx!

**Review by yeya24 — APPROVED** [review]
LGTM
