### PR TITLE
Store: If request ctx has an error we do not increment opsFailures counter

### LINKED ISSUE #3149: Store: Cancelled/Aborted GRPC Requests Increment thanos_objstore_bucket_operation_failures_total
**Thanos, Prometheus and Golang version used**:
**Thanos**: v0.13.0
**Prometheus**: 2.15.2
**Golang**: 1.14.1

**Object Storage Provider**:
GCS

**What happened**:
We noticed a continued increases in the `thanos_objstore_bucket_operation_failures_total` metric while not seeing errors in the log file. After looking at other metrics it appears that when a request from query is timed out/cancelled/aborted, the `thanos_objstore_bucket_operation_failures_total` metric increases. We also confirmed this from the GCS side by seeing an increased rate of `CANCELLED` API calls around the times we noticed that the bucket operation failures metric increased.

Screen Shot 2020-09-10 at 10 43 58 AM

**What you expected to happen**:
`thanos_objstore_bucket_operation_failures_total` not to increase.

**How to reproduce it (as minimally and precisely as possible)**:
Run a large query from querier that will hit its query timeout.

**Full logs to relevant components**:
I can include logs if desired but they just show normal block caching operations. Even in debug mode there is nothing about a failure.

### PR DESCRIPTION
**Pull request by ipstatic**
Signed-off-by: Jarod Watkins <jarod@42lines.net>

Resolves #3149 

* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

If a request is cancelled or times out we will no longer increment the ops failure counter.

### CODE REVIEW

File: pkg/objstore/objstore.go [hunk 1]
```diff
@@ -412,7 +412,7 @@ func (b *metricBucket) Delete(ctx context.Context, name string) error {
 
 	start := time.Now()
 	if err := b.bkt.Delete(ctx, name); err != nil {
-		if !b.isOpFailureExpected(err) {
+		if !b.isOpFailureExpected(err) && ctx.Err() == nil {
```
Comment (bwplotka) [inline pkg/objstore/objstore.go:415]:
```suggestion
		if !b.isOpFailureExpected(err) && ctx.Err() != context.Canceled {
```

**Review by bwplotka — COMMENTED** [review]
I believe we need to just skip `context.Canceled`. 

I think timeouts might be a legit failures, no?

File: pkg/objstore/objstore.go (hunk 1 above)
Comment (pracucci) [reply pkg/objstore/objstore.go:415]: Agree timeouts are legit failures, but this comment apply to any place, not just here, right? Also, is there a good reason why we don't we the `context.Canceled` check `isOpFailureExpected()`?

Comment (ipstatic) [reply pkg/objstore/objstore.go:415]: From what I have observed, cancelled requests can cause timeouts:
Screen Shot 2020-09-10 at 10 43 58 AM

If you notice, query cancels the request but store reports it as aborted. In my opinion that should be reported as cancelled, and not increase the error count.

Comment (ipstatic) [reply pkg/objstore/objstore.go:415]: or does Aborted != timeout?

Comment (ipstatic) [reply pkg/objstore/objstore.go:415]: > Agree timeouts are legit failures, but this comment apply to any place, not just here, right? Also, is there a good reason why we don't we the `context.Canceled` check `isOpFailureExpected()`?

If that is a better place for this then I have no problems making the change.

**Comment by ipstatic** [comment]
Is there a way for me to view the circleci results without giving them access to my Github account?

File: pkg/objstore/objstore.go (hunk 1 above)
Comment (bwplotka) [reply pkg/objstore/objstore.go:415]: `isOpFailureExpected` is really only for user specified function what to expect. I believe Cancel is valid to be ignored no matter what user specifies, no? (:

**Comment by bwplotka** [comment]
You shold have acces to logs, no? https://circleci.com/gh/thanos-io/thanos/11705?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ipstatic** [comment]
When I attempt to visit that URL, I get redirected to login via Github/Bitbucket and it requires read/write access to both public and private repos. I just didn't know if there was a way to view the logs "ready only" or not having to login at all.

**Comment by bwplotka** [comment]
Try incognito mode - works just fine (:

File: pkg/objstore/objstore.go (hunk 1 above)
Comment (pracucci) [reply pkg/objstore/objstore.go:415]: You're right @bwplotka 👍

Comment (ipstatic) [reply pkg/objstore/objstore.go]: I've updated the PR to use that context.

**Review by pracucci — APPROVED** [review]
LGTM

**Review by bwplotka — APPROVED** [review]
Amazing, thanks!

Some other solution at some point is to have error status as label (: 

Good enough for now +1

**Comment by ipstatic** [comment]
Thank you both!
