### PR TITLE
match external labels in exemplars API

### LINKED ISSUE #4116: query: query_exemplars does not account for external labels
@goku321

**Thanos, Prometheus and Golang version used**: v0.20.0 docker image

**Object Storage Provider**: gcs

**What happened**:
- configured ```--exemplar=...``` on our local and global queriers
- configure grafana for exemplars

**What you expected to happen**:
- grafana "time series" panel should show exemplars.
however...
the time series panel includes the full query from the panel, including external labels used by the local prom
instances.
the query\_range queries work as expected.
query\_exemplars did not.

If I send the query\_exemplars a query including the external labels, I get an empty response.
If I remove the external labels and just use labels the local prom instance knows about, I get responses.

**How to reproduce it (as minimally and precisely as possible)**:
- configure a prometheus with external labels, with sidecar
- configure thanos query to see the sidecar
- query thanos-query with the external labels.
(we have a second tier of queriers, but I do not think that is causing the issue.

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

Fixes #4116 

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Add logic of matching external labels in the exemplars API proxy.

The matching part is a little bit complex because the input is a query, which might contain multiple vector selectors.
We need to match each vector selector separately and construct the final query after all matches are processed.

## Verification

Tested locally and one unit test.
We don't have an E2E test for exemplars now so no E2E test added.

### CODE REVIEW

File: pkg/exemplars/proxy.go [hunk 1]
```diff
@@ -48,16 +52,80 @@ type exemplarsStream struct {
...
+	expr, err := parser.ParseExpr(req.Query)
+	if err != nil {
+		return err
+	}
+
+	selectors := parser.ExtractSelectors(expr)
+
+	newSelectors := make([][]*labels.Matcher, 0, len(selectors))
+	for _, matchers := range selectors {
+		matched, newMatchers:= matchesExternalLabels(matchers, s.selectorLabels)
```
Comment (kakkoyun) [inline pkg/exemplars/proxy.go:64]:
```suggestion
		matched, newMatchers := matchesExternalLabels(matchers, s.selectorLabels)
```

**Comment by kakkoyun** [comment]
Thanks, @yeya24, this looks amazing. I need to muster some brainpower to review this.

**Comment by yeya24** [comment]
@kakkoyun Thanks for the quick response. Yes it is a little bit complex and hard to review it directly from the code. It would be good to deploy it and test the external labels matching feature.

@tcolgate It would be good if you can help test this pr as well.

**Comment by tcolgate** [comment]
I've tested this change locally and we are now seeing exemplars on our staging environment (querying via both layers of thanos querier). LGTM

File: pkg/exemplars/proxy.go [hunk 2]
```diff
@@ -48,16 +52,80 @@ type exemplarsStream struct {
...
+			Start:                   req.Start,
+			End:                     req.End,
+			Query:                   query,
+			PartialResponseStrategy: req.PartialResponseStrategy,
+		}
+
 		es := &exemplarsStream{
-			client:  exemplarsClient,
-			request: req,
+
```
Comment (kakkoyun) [inline pkg/exemplars/proxy.go:126]:
```suggestion
```
nit

**Review by kakkoyun — APPROVED** [review]
LGTM
