### PR TITLE
fix store: handle invalid cache block dir

### LINKED ISSUE #1504: store: missing index.cache.json
**Thanos, Prometheus and Golang version used**
Thanos - `0.7.0`
Minio - `1.0.0-RELEASE.2019-08-14T20-37-41Z`

**What happened**
Thanos stopped to display some time ranges. After debugging it showed up those are blocks recently compacted and some downsampled. Thanos store logs contains lot of log lines about missing `index.cache.json` for those affected blocks. Looking to the folder of the store cache the folder for every of those blocks is there but empty. Looking to the OS the block is there looking good, `bucket verify` does not report anything.

Once deleted those empty folders and restarting thanos-stores everything is working fine.

It happened after upgrading from 0.6.0 to 0.7.0 

**Full logs to relevant components**

```
level=warn ts=2019-09-05T21:44:36.827064704Z caller=bucket.go:325 msg="error parsing block range" block=01DM0VRMH45C162YN1WR59YW99 err="read meta.json: open /var/thanos/store/01DM0VRMH45C162YN1WR59YW99/meta.json: no such file or directory"
level=warn ts=2019-09-05T21:44:36.826155442Z caller=bucket.go:325 msg="error parsing block range" block=01DKZYJ3CFVR9RD0YRCVDVTFWF err="read meta.json: open /var/thanos/store/01DKZYJ3CFVR9RD0YRCVDVTFWF/meta.json: no such file or directory"
level=warn ts=2019-09-05T21:44:36.826555207Z caller=bucket.go:325 msg="error parsing block range" block=01DM0FX9SFQV1PW1W31XTCZSAN err="read meta.json: open /var/thanos/store/01DM0FX9SFQV1PW1W31XTCZSAN/meta.json: no such file or directory"
level=warn ts=2019-09-05T21:44:36.826213195Z caller=bucket.go:325 msg="error parsing block range" block=01DM01JJP0RFYMQ76ZAHD1HY5H err="read meta.json: open /var/thanos/store/01DM01JJP0RFYMQ76ZAHD1HY5H/meta.json: no such file or directory"
level=warn ts=2019-09-05T21:44:36.826576288Z caller=bucket.go:325 msg="error parsing block range" block=01DM0N7BWMN84T2Q7YEZ4ZK8WM err="read meta.json: open /var/thanos/store/01DM0N7BWMN84T2Q7YEZ4ZK8WM/meta.json: no such file or directory"
level=warn ts=2019-09-05T21:44:27.716935333Z caller=bucket.go:325 msg="error parsing block range" block=01DM0VRMH45C162YN1WR59YW99 err="read meta.json: open /var/thanos/store/01DM0VRMH45C162YN1WR59YW99/meta.json: no such file or directory"
level=warn ts=2019-09-05T21:44:27.715856734Z caller=bucket.go:325 msg="error parsing block range" block=01DM0EWQWM0SQPHDQMH56H2FGR err="read meta.json: open /var/thanos/store/01DM0EWQWM0SQPHDQMH56H2FGR/meta.json: no such file or directory"
level=warn ts=2019-09-05T21:44:27.715545478Z caller=bucket.go:325 msg="error parsing block range" block=01DM01JJP0RFYMQ76ZAHD1HY5H err="read meta.json: open 
```

### PR DESCRIPTION
**Pull request by FUSAKLA**
fixes #1504

* [x] CHANGELOG entry if change is relevant to the end user.

## Changes
- store: delete block dir with missing `meta.json` on startup

### CODE REVIEW

**Comment by FUSAKLA** [comment]
CI failing in master, will rebase once fixed

**Comment by FUSAKLA** [comment]
@GiedriusS Should be moved as you suggested, PTAL if that is what you meant.

File: pkg/block/block.go [hunk 1]
```diff
@@ -153,3 +153,10 @@ func IsBlockDir(path string) (id ulid.ULID, ok bool) {
 	id, err := ulid.Parse(filepath.Base(path))
 	return id, err == nil
 }
+
+func HasMetaFile(blockPath string) bool {
```
Comment (bwplotka) [inline pkg/block/block.go]: I am against this shallow function - such helper is not needed - the oneliner below is exactly enough for this.

In the same way, there is no `Max(a, b)` function is go standard library. You just do this one `if ` on your own (: 
What do you think, can we just inline this logic?

Comment (GiedriusS) [reply pkg/block/block.go]: We could do what @bwplotka suggests, it might be neater. :+1:

Comment (FUSAKLA) [reply pkg/block/block.go]: I eventually simplified it to checking directly for the meta file which should also provide the check for the directory existence right away. The creation of dir is agnostic to it's existence and new downloaded files should overwrite those existing in the block dir. 

Thanks @bwplotka for pointing this out I just saw the `IsBlockDir` func so I somehow followed the pattern.
