### PR TITLE
Upload blocks with the lowest minTime first

### LINKED ISSUE #1670: sidecar: Upload blocks from oldest
Ref: https://cloud-native.slack.com/archives/CK5RSSC10/p1571650833206600

It can happen during long network partition that uploaded blocks in the wrong order can cause compactor to miss one block during compaction. This results in overlapping blocks - compactor halts in that case. Read path works.

AC:
* Sort local blocks based on min/max time
* Optional: Add repair for verifier with vertical compaction - this will allow manual repair for those case (the alternative is to change a bit different meta to the overlapped block OR remove it)

### PR DESCRIPTION
**Pull request by obiesmans**
Fixes #1670

Signed-off-by: Olivier Biesmans <olivier.biesmans@blablacar.com>

* [x] I added CHANGELOG entry for this change.

## Changes

Sidecar now uploads blocks with the lowest minTime first

### CODE REVIEW

**Comment by obiesmans** [comment]
Work in progress. But feedback is already welcome. 
I'd like to add a repair for `thanos bucket verify` althought I have no idea how to fix the vertical compression issues except by deleting one of the overlapping blocks.

File: pkg/shipper/shipper_test.go [hunk 1]
```diff
@@ -77,3 +79,132 @@ func TestShipperTimestamps(t *testing.T) {
...
+						MinTime: int64(i * 1000),
+						Version: 1,
+					},
+				},
+			),
+		)
+	}
+	rand.Shuffle(len(metas), func(i, j int) {
+		metas[i], metas[j] = metas[j], metas[i]
+	})
```
Comment (bwplotka) [inline pkg/shipper/shipper_test.go]: Why are we not resetting timer here?

File: pkg/shipper/shipper_test.go [hunk 2]
```diff
@@ -77,3 +79,132 @@ func TestShipperTimestamps(t *testing.T) {
...
+	b.ResetTimer()
+
+	shipper := New(nil, nil, dir, nil, nil, metadata.TestSource)
+	if err := shipper.iterBlockMetas(func(m *metadata.Meta) error {
```
Comment (bwplotka) [inline pkg/shipper/shipper_test.go]: Can we remove this function? I think you left it to compare benchmarks but actually the proper flow would be to create a benchmark for old thing, then have new commit with new function and tested in the same benchmark name so we can use something like this: https://github.com/prometheus/prombench/tree/master/funcbench (: or https://godoc.org/golang.org/x/tools/cmd/benchcmp

**Comment by bwplotka** [comment]
Also can we have BlaBla car badge on our website? (: https://thanos.io/ ([here](https://thanos.io/contributing/how-to-contribute-to-docs.md/#adopters-logos) is how to add it)

File: pkg/shipper/shipper_test.go (hunk 2 above)
Comment (obiesmans) [reply pkg/shipper/shipper_test.go]: Didn't know about those tools, I'll remove the old `iterBlockMetas()`.

**Comment by obiesmans** [comment]
For the benchmarks, there's basically no difference : the number of blocks is quite low and the blocks are almost sorted. 
While `sort.Slice()` relies on quicksort, which doesn't do very well on almost sorted data, I don't think it's worth looking further on a low number of blocks (100 2-hours blocks is already more that 8 days retention).


```
goos: darwin
goarch: amd64
pkg: github.com/thanos-io/thanos/pkg/shipper
BenchmarkIterBlockMetas-8         	1000000000	         0.0236 ns/op
BenchmarkIterSortedBlockMetas-8   	1000000000	         0.0207 ns/op
PASS
ok  	github.com/thanos-io/thanos/pkg/shipper	9.861s
```

File: pkg/shipper/shipper_test.go (hunk 1 above)
Comment (obiesmans) [reply pkg/shipper/shipper_test.go]: Nice catch.

File: pkg/shipper/shipper_test.go (hunk 2 above)
Comment (obiesmans) [reply pkg/shipper/shipper_test.go]: Deleted !

File: pkg/shipper/shipper_test.go [hunk 3]
```diff
@@ -77,3 +79,85 @@ func TestShipperTimestamps(t *testing.T) {
...
+						ULID:    id,
+						MaxTime: int64((i + 1) * 1000),
+						MinTime: int64(i * 1000),
+						Version: 1,
+					},
+				},
+			),
+		)
+	}
+	rand.Shuffle(len(metas), func(i, j int) {
```
Comment (bwplotka) [inline pkg/shipper/shipper_test.go]: I would vote for actually organizing initial metas ourselves. Relying on some random shuffling is not really deterministic.

File: pkg/shipper/shipper_test.go [hunk 4]
```diff
@@ -77,3 +79,85 @@ func TestShipperTimestamps(t *testing.T) {
...
+		return nil
+	}); err != nil {
+		testutil.Ok(t, err)
+	}
+	testutil.Equals(t, sort.SliceIsSorted(metas, func(i, j int) bool {
+		return metas[i].BlockMeta.MinTime < metas[j].BlockMeta.MinTime
+	}), true)
+}
+
+func BenchmarkIterBlockMetas(b *testing.B) {
```
Comment (bwplotka) [inline pkg/shipper/shipper_test.go]: They are much more interesting functions we could profile then this - it is fairly simple, but no harm in keeping this (:

File: pkg/shipper/shipper_test.go (hunk 3 above)
Comment (obiesmans) [reply pkg/shipper/shipper_test.go]: Ok.

File: pkg/shipper/shipper_test.go (hunk 4 above)
Comment (obiesmans) [reply pkg/shipper/shipper_test.go]: Yes I went overboard with this ;)
