### PR TITLE
Route parse errors from sharding through normal api path

### LINKED ISSUE #5683: Parse errors are returned in a different format from the query-frontend query api when vertical sharding is enabled
**Thanos, Prometheus and Golang version used**: 

thanos, version 0.29.0-dev (branch: main, revision: 0d659bf171afa6bdf5c5ece3033df3a7e8245d8c)
  build user:       root@8821bbde0c60
  build date:       20220909-15:00:44
  go version:       go1.18.6
  platform:         linux/amd64

**Object Storage Provider**:
GCS

**What happened**:
When sending a query to the query-frontend with vertical sharding enabled, parse errors are returned with a 500 response code and plaintext format

**What you expected to happen**:
Parse errors returned as json, with a 400 response code.  This format is expected by grafana to properly render the parse error.

**How to reproduce it (as minimally and precisely as possible)**:
* Run a query-frontend with the `--query-frontend.vertical-shards` flag set to > 1
* Send a query to either `/api/v1/query` or `/api/v1/query_range` with a malformed query param (e.g., `foo(`)

### PR DESCRIPTION
**Pull request by sdufel**
When the parser used in the querySharder encounters a parse error, it returns that error back through to the API without the normal api error wrapper.  This results in parse errors being sent back with a 500 response code rather than a 400 response code, and the UI (thanos ui, grafana) treats errors as a generic server error rather than a client-side error.

Fixes #5683 

Signed-off-by: Samuel Dufel <samuel.dufel@shopify.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes
Break out of the sharding middleware in the event of a parse error and pass the request along the chain to ensure that all api errors are processed in the same location.

## Verification
Manually verified api responses before and after the change

### CODE REVIEW

File: pkg/queryfrontend/shard_query.go [hunk 1]
```diff
@@ -55,11 +55,8 @@ type querySharder struct {
 
 func (s querySharder) Do(ctx context.Context, r queryrange.Request) (queryrange.Response, error) {
 	analysis, err := s.queryAnalyzer.Analyze(r.GetQuery())
```
Comment (yeya24) [inline pkg/queryfrontend/shard_query.go:57]: I am wondering which case it will return error. @sdufel Can you provide your queries?

Comment (sdufel) [reply pkg/queryfrontend/shard_query.go:57]: It seems to be an issue in cases of mismatched parentheses or curly braces.  I don't have an exhaustive list, but Imagine any query which isn't syntactically correct triggers this issue.
For instance `foo(` is a minimal query with which you can see the problem.

Comment (yeya24) [reply pkg/queryfrontend/shard_query.go:57]: I see. Thanks for the explanation.

**Review by yeya24 — APPROVED** [review]
This change makes sense to me. Probably @fpetkovski can take another look?

**Review by fpetkovski — APPROVED** [review]
Thanks, this makes sense to me 👍
